### ISSUE TITLE
Hanging on Binance 400, request to use coincap.io or other as backup to Binance

### ISSUE THREAD

**Issue by esarmstrong** [mitchglass97/Mint-Crypto-Chrome#1]
Howdy! Not sure if this project is still being maintained with more and more crypto platforms integrating directly with Mint, but I tried it today with DOT (polkadot) and ran into what I think is a bug. I believe the issue occurs when the request to Binance's API is formed: `stringAPI = "https://api.binance.us/api/v3/avgPrice?symbol=" + coinData[i].coinName + "USD";` where `DOTUSD` is not a valid conversion on Binance (maybe `DOTUSDT` instead?). So getting an error response from Binance, the extension seems to just hang for me on the update screen.

I pulled the extension down locally and found that swapping Binance's API out with coincap.io's has solved the issue, but I know a lot of folks prefer Binance. I wonder if we can use Binance, catch the error if any and try coincap.io (or another), and as a last resort look at throwing some sort of "coin not found" error? Happy to open a PR if this sounds good.

First ever issue, let me know if you have any confusion or questions. Appreciate the extension, just got Mint and found a crypto-shaped hole when I couldn't sync with my platform :)

**Comment by mitchglass97** [comment]
Ooh nice! Sounds good to me as long as the limit on free requests to the new API isn't too low. 

There's also an issue with the current API not returning the right price for XRP, I wonder if this could fix that too.

**Comment by esarmstrong** [comment]
Near as I can tell there's no rate-limiting on coincap's side, so think we're gtg there. Do you have any resources for local dev and testing with chrome extensions? Think it's an easy change, just not sure how to test it / bundle the extension on my end 😅

**Comment by mitchglass97** [comment]
Yeah just run npm install to install the dependencies then run npm start to run the program.

To load the extension on Chrome: 
1) Go to chrome://extensions
2) Check Developer mode
3) Click on Load unpacked extension
4) Select the build folder

**Comment by mitchglass97** [comment]
I ended up implementing this. Thanks for your help Evan!
